SELECT C.CODE,
	C.NAME,
	ROUND(AVG(PS.L2H),
		2) AS AVG_L2H,
	ROUND(AVG(PS.O2C),
		2) AS AVG_O2C
FROM COMPANY.STATE S
LEFT JOIN COMPANY.CODE C ON S.CODE = C.CODE
LEFT JOIN COMPANY.DETAIL D ON C.CODE = D.CODE
LEFT JOIN
	(SELECT *
		FROM HIST.PRICE_STOCK
		WHERE 1 = 1
			AND P_DATE BETWEEN 20210601 AND 20210602
		GROUP BY CODE,
			P_DATE) PS ON C.CODE = PS.CODE
WHERE 1 = 1
	AND S.STOP IS FALSE
	AND D.MARKET = 'KOSPI'
GROUP BY C.CODE
ORDER BY AVG_L2H DESC
LIMIT 10