version: '3.8'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      TZ: Asia/Seoul 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      TZ: Asia/Seoul 
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    volumes: 
      - mongo-express-data:/data/db
    depends_on: 
      - mongo

volumes:
  mongo-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "C:\\Users\\cheolgyu\\volume\\mongo"
  mongo-express-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "C:\\Users\\cheolgyu\\volume\\mongo-express"