version: '3.1'
services:

  db:
    image: postgres
    restart: always
    command: postgres -c 'max_connections=100'
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: dev
      TZ: Asia/Seoul
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080