version: '3.1'
services:

  db:
    image: postgres
    restart: always
    command: postgres -c 'max_connections=100'
    volumes:
      - C:\\Users\\cheolgyu\\postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: dev
      TZ: Asia/Seoul
      # 이어서 시작할때 필요함. 기존데이터로 시작함.
      POSTGRES_CONFIG_hot_standby: "on"
    ports:
      - 5432:5432

  adminer:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=my@mail.com
      - PGADMIN_DEFAULT_PASSWORD=PassW@rd!!
    restart: always
    ports:
      - 8080:80