version: '3.8'
services:
  db:
    image: postgres
    restart: always
    command: postgres -c 'max_connections=100'
    volumes:
      - pq-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: dev
      TZ: Asia/Seoul
      # 이어서 시작할때 필요함. 기존데이터로 시작함.
      POSTGRES_CONFIG_hot_standby: "on"
    ports:
      - 5432:5432
volumes:
  pq-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "./volume/postgresql"
