DROP VIEW IF EXISTS "public.daily";

CREATE VIEW public.daily AS
SELECT C.*,
	B.CP_X1,
	B.CP_Y1,
	B.CP_X2,
	B.CP_Y2,
	B.CP_X_TICK,
	B.CP_Y_MINUS,
	B.CP_Y_PERCENT,
	B.OP_X1,
	B.OP_Y1,
	B.OP_X2,
	B.OP_Y2,
	B.OP_X_TICK,
	B.OP_Y_MINUS,
	B.OP_Y_PERCENT,
	B.LP_X1,
	B.LP_Y1,
	B.LP_X2,
	B.LP_Y2,
	B.LP_X_TICK,
	B.LP_Y_MINUS,
	B.LP_Y_PERCENT,
	B.HP_X1,
	B.HP_Y1,
	B.HP_X2,
	B.HP_Y2,
	B.HP_X_TICK,
	B.HP_Y_MINUS,
	B.HP_Y_PERCENT,
	ARRAY_AGG(S.*)
FROM COMPANY.CODE C
LEFT JOIN PUBLIC.BOUND B ON C.CODE = B.CODE
LEFT JOIN COMPANY.STATE S ON B.CODE = S.CODE
GROUP BY C.CODE,
	B.CODE,
	S.CODE
ORDER BY B.CP_Y_PERCENT DESC